module.exports ={
  NULLGROUP: "该商家暂无团购活动商品",
  NULLSPECIALS: "该商家暂无特惠活动商品",
  DATAFAIL: "获取数据失败",
  OPENPOSITION:'请先开启您手机的定位功能!',
  OPENPHONEPOSITION:'为能检测到请您的定位信息，请先开启手机的定位服务！',
  UNAUTHORIZED:'抱歉！您还有必须授权信息未授权,请授权后进行操作!',
  NULLSEARCH:'搜索内容不能为空',
  FAILREQ:'请求接口失败',
  UNFOLLOW:'是否取消关注当前店铺',
  WRITEOFF:"确定后，此订单将成为已消费状态，如您还未消费，请谨慎操作！",
  COLLECTGOODS:"是否确认收货？",
  DELETEORDER:"是否确认删除此订单？",
  DELETEIMG:"是否删除这张图片？",
  CANCELCOLLECT:'是否取消收藏当前商品',
  NULLORDER:"暂时没有订单",
  EVALUATIONSUCCESS:"评价成功!",
  NULLLOGISTICS:"暂无物流信息",
  NULLEVALUATION:"您还没有任何评价，先去逛逛吧",
  NULLSHARE: "您还没有待分享活动，先去逛逛吧",
  NULLABOUT:"您还没有关注的店铺，先去逛逛吧",
  NULLSTORE:"您还没有浏览过商品，先去逛逛吧",
  NULLCOLLECTSHOP:'您还没有收藏商品，先去逛逛吧',
  DELETEEVALUATION:"是否删除此评论？",
  DELETESUCCESS:"成功删除！",
  NULLBALANCE:"暂无资金明细",
  BALANCEEXPLAIN:"支持提现类型：拼团立减金额",
  BALANCENOTENOUGH:"可提现金额不足",
  SPECIALCARDLISTNULL:"获取专享卡失败",
  RECORDSOFCONSUMPTION:"请求消费记录列表失败",
  EMPTYLIST:"确认清空吗?",
  EMPTYADDRESS:"确定删除吗？",
  NULLADDRESS:"您还没有收货地址，快去添加吧",
  PHONEERR:"手机号不正确，请重新输入手机号",
  EXCEED:"已超过限购数",
  LEASTONE:"购买数量不能小于一件",
  OUTOFSTOCK: "购买不能大于库存",
  BALANCEPAY:"是否使用余额支付？",
  WRONGPHONE:"请输入正确的手机号码",
  SAVEIMGSUCESS:'保存图片成功',
  OPENIMGPERMISSION:'是否前往开启保存图片权限?',
  GROUPING:'正在拼团',
  MAX5:'最多显示5个团购',
  SAVESUCESS:'保存成功',
  SENTVERIFICODE:'验证码已发送',
  SUSPENDAPPLICATION:'暂停商家申请',
  INPUTALLINFO:'请输入全部信息',
  WRONGVERFIFYCODE:'请输入正确的验证码',
  CONTACTYOU:'工作人员将在1-3个工作日联系您',
  NEEDPERMISSION:'需要用户权限',
  LOWVERSION:'版本太低',
  UPGRADEWECHAT:'您的微信基础版本库过低，请升级微信或使用原版微信进行体验！',
  ERROR:'错误',
  MODEFIYSUCC:'修改成功！',
  WRONGNICKNAME:'请输入正确格式的昵称!',
  INPUTREALNAME:'请输入真实姓名',
  INPUTRIGHTZFB:'请输入正确的支付宝账号',
  INPUTNAME:'请输入联系人姓名',
  CLEARSEACH:"确定清空历史搜索吗？",
  PURCHASE:"您已达到限购数",
  SAVEECV:"评论不能为空",
  CODEDATAERR: "二维码信息错误，请进入店铺" ,
  EVALUATISTRING:"仅支持输入汉字、数字、英文以及常用符号！"
}